name: prepare
description: "Prepare the environment for the build"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4.1.0
    - name: Install Packages - LibSodium, nssdb
      shell: bash
      run: |-
        sudo apt-get update
        sudo apt-get install -y libsodium23 libsodium-dev libjemalloc-dev apt-transport-https haveged libnss3-tools
        sudo service haveged restart
        java --version
    - uses: "./.github/actions/restore_gradle_cache"